version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql121
      MYSQL_DATABASE: todo
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3307:3306"

  backend:
    build: ./backend
    container_name: java-backend
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    working_dir: /app
    volumes:
      - ./backend/.env:/app/.env
    networks:
      - app-net

  frontend:
    build: ./frontend
    container_name: nextjs-frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
    networks:
      - app-net
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080  # or set actual API URL

volumes:
  mysql-data:

networks:
  app-net:
    driver: bridge
